### ISSUE TITLE
Missing dGeomSetData dGeomGetData and more

### ISSUE THREAD

**Issue by anderssoft** [Ricku34/ODE.js#4]
Hi! 
I  think the object Set/GetData functions i missing.

dBodySetData/dBodyGetData
dGeomSetData/dGeomGetData
etc.

If you can add the emscripten build files and build instructions then I would be glad to help out adding missing functions.

**Comment by Ricku34** [comment]
Ok I understand the interest of adding custom data to ODE objects.

I'm going to set up a special memory heap for JavaScript references from the ODE lib so that the following test works:
```
   var world = new ODE.World();
   var space = new ODE.Space.Hash();
   console.assert(world && space);
 
   var sph1 = ODE.Geom.createSphere(3);
   var sph2 = ODE.Geom.createSphere(3);
   sph1.name = "sphere 1";
   sph2.name = "sphere 2";
   
  
   var body = world.createBody();
   sph1.setBody(body);
   console.assert(sph1.getBody()===body);
  
   sph1.setPosition(-1,0,1);
   sph2.setPosition(1,0,0);
   space.add(sph1);
   space.add(sph2);
  
   space.collide(function(g1,g2)
   {
       console.log('Collide ', g1.name, g2.name);
   })
```

**Comment by Ricku34** [comment]
OK i've  just push a fix ! this will works for all jaavascript ref except for : 

- **ODE.World** & **ODE.Space** this normaly are singleton objects
- **ODE.Contact** this object is created only by the function **ODE.Geom.collide** its lifespan does not exceed more than collide time
- **ODE.Mass** , when you set mass to a body , all mass parameters are duplicated into body and Body **getMass** method return body mass parameters into a new instance of **ODE.Mass**  object
